replicaCount: 1
image:
  repository: mycluster-registry:5000/nginx
  tag: v8.0
  pullPolicy: Always
restartPolicy: Never
sleepyTime: "10"
index: <h1>Hello</h1> <p>This is a test123</p>
service:
  annotations: {}
  externalIPs: []
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  type: ClusterIP
  port: 8888
  nodePort: ""
podAnnotations: {}
resources: {}
nodeSelector: {}
